version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - app_network
    depends_on:
      - app_postgres
    restart: unless-stopped

  app_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    networks:
      - app_network
    ports:
      - 55433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all" ]

#  goose:
#    image: stonys/goose-migrate
#    volumes:
#      - ./migrations:/migrations
#    networks:
#      - app_network
#    depends_on:
#      - app_postgres
#    entrypoint:
#      - goose
#      - -dir
#      - /migrations
#      - postgres
#      - postgres://postgres:postgres@app_postgres:5432/test_db?sslmode=disable
#      - up

networks:
  app_network:

volumes:
  pgdata: